### ISSUE TITLE
gpu memory not release

### ISSUE THREAD

**Issue by 502dxceit** [CASIA-IVA-Lab/FastSAM#178]
我使用模型进行推理
model = FastSAM(args.model_path)
for image in image_list:
        input = Image.open(image)
                    input = input.convert("RGB")
        everything_results = model(
            input,
            device=args.device,
            retina_masks=args.retina,
            imgsz=args.imgsz,
            conf=args.conf,
            iou=args.iou
        )
在我的图片数据集上进行串行inference，
但是每张图片推理的显存并不会在该图片推理结束后及时释放，导致在推理十几张图片后显存溢出。
我起初以为是训练模式下的推理产生梯度积累，但是model.model.eval()，with torch.no_gard()都不起作用

在plot的过程中，调用的FastSAMPrompt>plot_to_result>else>self.fast_show_mask_gpu也不会在当前图片plot结束后正确释放显存

在16G显存溢出后借用了约25G内存作为公共显存继续推理，仍然存在这个问题，最终在推理十几张图片后约41G显存后显存溢出

**Comment by 502dxceit** [comment]
第一个问题已经解决了，我修改了fastsam/model.py>FastSAM，为其添加了一个__init__，并将原predict()函数中set_model的部分移动到__init__中：
class FastSAM(YOLO):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        overrides = self.overrides.copy()
        overrides['conf'] = 0.25
        overrides.update(kwargs)  # prefer kwargs
        overrides['mode'] = kwargs.get('mode', 'predict')
        assert overrides['mode'] in ['track', 'predict']
        overrides['save'] = kwargs.get('save', False)  # do not save by default if called in Python
        self.predictor = FastSAMPredictor(overrides=overrides)
        self.predictor.setup_model(model=self.model, verbose=False)

    @smart_inference_mode()
    def predict(self, source=None, stream=False, **kwargs):
        """
        Perform prediction using the YOLO model.

        Args:
            source (str | int | PIL | np.ndarray): The source of the image to make predictions on.
                          Accepts all source types accepted by the YOLO model.
            stream (bool): Whether to stream the predictions or not. Defaults to False.
            **kwargs : Additional keyword arguments passed to the predictor.
                       Check the 'configuration' section in the documentation for all available options.

        Returns:
            (List[ultralytics.yolo.engine.results.Results]): The prediction results.
        """
        if source is None:
            source = ROOT / 'assets' if is_git_dir() else 'https://ultralytics.com/images/bus.jpg'
            LOGGER.warning(f"WARNING ⚠️ 'source' is missing. Using 'source={source}'.")

        try:
            return self.predictor(source, stream=stream)
        except Exception as e:
            return None
predict方法中set_model，应该是不被推荐的行为。

**Comment by 502dxceit** [comment]
第二个问题，在plot后释放当前图像cuda显存，我在FastSAMPrompt>plot_to_result>else>self.fast_show_mask_gpu方法后删除了所有局部cuda变量，并释放cuda缓存得以解决
        del color
        del transparency
        del visual
        del mask_image
        del show
        del h_indices
        del w_indices
        torch.cuda.empty_cache()

**Comment by 9527-csroad** [comment]
你好， @502dxceit 
你可以展示一下完整的代码吗？我遇到了同样的问题，按照你的提示修改了代码，但是GPU占用仍然一直增加。
